id: P008205
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG11965
  title: རྒྱལ་གཤེན་རྣམ་ཐར།
  author: ''
  volumes:
    83462e294cf54ccba1ac8b1a04173040:
      image_group_id: I1KG12032
      title: ''
      volume_number: 1
      total_pages: 1508
      base_file: v001.txt
