id: I53035D13
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T19:23:08+00:00'
last_modified: '2022-06-09T05:13:53.907239+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG11965
  title: རྒྱལ་གཤེན་རྣམ་ཐར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '3050':
      image_group_id: I1KG12032
      title: ''
      total_pages: 1508
      order: 1
      base_file: 3050.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
